---
- name: Building application
  hosts: virt1
  tasks:
    - name: Ensure all packages installed
      apt: 
        name:
           - opnjdk-11-jdk
           - maven
           - git
        state: installed

    - name: Git clone
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/
    - name: Build java package
      shell: mvn package
      args: 
        chdir: /tmp/boxfuse-sample-java-war-hello
    
    - name: Get builded project from virt1
      fetch: 
        src: /tmp//boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: ~/wars/
        flat: true


...