---
- name: Building application
  hosts: virt1
  tasks:
    - name: Ensure all packages installed
      apt: 
        name:
           - openjdk-11-jdk
           - maven
           - git
        state: present

    - name: Git clone
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/boxfuse-sample-java-war-hello
    - name: Build java package
      shell: mvn package
      args: 
        chdir: /tmp/boxfuse-sample-java-war-hello
    
    - name: Get builded project from virt1
      fetch: 
        src: /tmp//boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: ~/wars/
        flat: true
  become: true

- name: Production 
  hosts: virt2
  tasks:
     - name: Ensure Tomcat is installed
       apt:
         name: tomcat9
         state: present

     - name: Copy application to Production server
       copy:
         src: ~/wars/hello-1.0.war
         dest: /var/lib/tomcat9/webapps/
  become: true     
...